// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuentinhasDaTininha.Infraestrutura.Persistencia;

#nullable disable

namespace QuentinhasDaTininha.Infraestrutura.Persistencia.Migrations
{
    [DbContext(typeof(QuentinhasDaTininhaDbContext))]
    [Migration("20260807170300_SincronizarFreteCepAliasExistentes")]
    partial class SincronizarFreteCepAliasExistentes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.Acompanhamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstaDisponivel")
                        .HasColumnType("boolean");

                    b.Property<string>("GrupoExclusivo")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("MotivoIndisponibilidade")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("OrdemExibicao")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecoAdicional")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("TipoSelecao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("acompanhamento", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.CardapioDia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DiaSemana")
                        .IsUnique();

                    b.ToTable("cardapio_dia", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.CardapioDiaPrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardapioDiaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EstaDisponivel")
                        .HasColumnType("boolean");

                    b.Property<int>("OrdemExibicao")
                        .HasColumnType("integer");

                    b.Property<Guid>("PratoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PratoId");

                    b.HasIndex("CardapioDiaId", "PratoId")
                        .IsUnique();

                    b.ToTable("cardapio_dia_prato", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EstaAtiva")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrdemExibicao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("categoria", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.ConfiguracaoRestaurante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AceitaPedidos")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cep")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("HorarioFuncionamento")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Instagram")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("MensagemAberto")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("MensagemFechado")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("ModoFuncionamento")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UrlImagemCapa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UrlLogotipo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Whatsapp")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("configuracao_restaurante", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.FechamentoExcepcional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataFechamento")
                        .HasColumnType("date");

                    b.Property<bool>("DiaInteiro")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly?>("HoraFim")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<string>("MensagemCliente")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Motivo")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("PermitirPedidos")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DataFechamento");

                    b.HasIndex("DataFechamento", "EstaAtivo");

                    b.ToTable("fechamento_excepcional", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.FreteBairro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("BairroNormalizado")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("BairroNormalizado")
                        .IsUnique();

                    b.ToTable("frete_bairro", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.FreteBairroAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("AliasNormalizado")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("AliasNormalizado");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("Ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AtualizadoEm");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CriadoEm");

                    b.Property<Guid>("FreteBairroId")
                        .HasColumnType("uuid")
                        .HasColumnName("FreteBairroId");

                    b.Property<bool>("GeradoAutomaticamente")
                        .HasColumnType("boolean")
                        .HasColumnName("GeradoAutomaticamente");

                    b.HasKey("Id");

                    b.HasIndex("AliasNormalizado")
                        .IsUnique();

                    b.HasIndex("Ativo");

                    b.HasIndex("FreteBairroId");

                    b.ToTable("frete_bairro_alias", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.FreteCep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("Ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AtualizadoEm");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("Cep");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CriadoEm");

                    b.Property<Guid>("FreteBairroId")
                        .HasColumnType("uuid")
                        .HasColumnName("FreteBairroId");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("Cep")
                        .IsUnique();

                    b.HasIndex("FreteBairroId");

                    b.ToTable("frete_cep", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.GrupoAcompanhamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("grupo_acompanhamento", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.GrupoAcompanhamentoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcompanhamentoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GrupoAcompanhamentoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("boolean");

                    b.Property<int>("OrdemExibicao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AcompanhamentoId");

                    b.HasIndex("GrupoAcompanhamentoId", "AcompanhamentoId")
                        .IsUnique();

                    b.ToTable("grupo_acompanhamento_item", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.HistoricoAlteracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Acao")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DadosAnteriores")
                        .HasColumnType("text");

                    b.Property<string>("DadosNovos")
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("EntidadeId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoEntidade")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("UsuarioAdministrativoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioAdministrativoId");

                    b.HasIndex("TipoEntidade", "EntidadeId");

                    b.ToTable("historico_alteracao", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.HorarioFuncionamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly>("HoraAbertura")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraFechamento")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DiaSemana", "HoraAbertura", "HoraFechamento")
                        .IsUnique();

                    b.ToTable("horario_funcionamento", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Bairro")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataPedido")
                        .HasColumnType("date");

                    b.Property<string>("EnderecoEntrega")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("PrecisaTroco")
                        .HasColumnType("boolean");

                    b.Property<string>("Referencia")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("TelefoneCliente")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TipoEntrega")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("ValorFrete")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("ValorSubtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("ValorTroco")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("DataPedido");

                    b.HasIndex("FormaPagamento");

                    b.HasIndex("TipoEntrega");

                    b.ToTable("pedido", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.PedidoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Acompanhamentos")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomePrato")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PratoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tamanho")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("PratoId");

                    b.ToTable("pedido_item", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.Prato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EhDestaque")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstaDisponivel")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("GrupoAcompanhamentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("MotivoIndisponibilidade")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("OrdemExibicao")
                        .HasColumnType("integer");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("UrlImagem")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EstaAtivo");

                    b.HasIndex("EstaDisponivel");

                    b.HasIndex("GrupoAcompanhamentoId");

                    b.HasIndex("Nome");

                    b.HasIndex("OrdemExibicao");

                    b.ToTable("prato", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.PratoAcompanhamento", b =>
                {
                    b.Property<Guid>("PratoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcompanhamentoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EhObrigatorio")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstaIncluido")
                        .HasColumnType("boolean");

                    b.Property<int?>("QuantidadeMaxima")
                        .HasColumnType("integer");

                    b.HasKey("PratoId", "AcompanhamentoId");

                    b.HasIndex("AcompanhamentoId");

                    b.ToTable("prato_acompanhamento", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.PrecoPrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("PratoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tamanho")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("PratoId", "Tamanho", "FormaPagamento")
                        .IsUnique();

                    b.ToTable("preco_prato", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.UsuarioAdministrativo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("UltimoAcessoEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuario_administrativo", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.CardapioDiaPrato", b =>
                {
                    b.HasOne("QuentinhasDaTininha.Dominio.Entidades.CardapioDia", "CardapioDia")
                        .WithMany("CardapiosDiaPratos")
                        .HasForeignKey("CardapioDiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuentinhasDaTininha.Dominio.Entidades.Prato", "Prato")
                        .WithMany("CardapiosDiaPratos")
                        .HasForeignKey("PratoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CardapioDia");

                    b.Navigation("Prato");
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.FreteBairroAlias", b =>
                {
                    b.HasOne("QuentinhasDaTininha.Dominio.Entidades.FreteBairro", "FreteBairro")
                        .WithMany("Aliases")
                        .HasForeignKey("FreteBairroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FreteBairro");
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.FreteCep", b =>
                {
                    b.HasOne("QuentinhasDaTininha.Dominio.Entidades.FreteBairro", "FreteBairro")
                        .WithMany("Ceps")
                        .HasForeignKey("FreteBairroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FreteBairro");
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.GrupoAcompanhamentoItem", b =>
                {
                    b.HasOne("QuentinhasDaTininha.Dominio.Entidades.Acompanhamento", "Acompanhamento")
                        .WithMany("GruposAcompanhamentoItens")
                        .HasForeignKey("AcompanhamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuentinhasDaTininha.Dominio.Entidades.GrupoAcompanhamento", "GrupoAcompanhamento")
                        .WithMany("Itens")
                        .HasForeignKey("GrupoAcompanhamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acompanhamento");

                    b.Navigation("GrupoAcompanhamento");
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.HistoricoAlteracao", b =>
                {
                    b.HasOne("QuentinhasDaTininha.Dominio.Entidades.UsuarioAdministrativo", "UsuarioAdministrativo")
                        .WithMany("HistoricosAlteracao")
                        .HasForeignKey("UsuarioAdministrativoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UsuarioAdministrativo");
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.PedidoItem", b =>
                {
                    b.HasOne("QuentinhasDaTininha.Dominio.Entidades.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuentinhasDaTininha.Dominio.Entidades.Prato", "Prato")
                        .WithMany()
                        .HasForeignKey("PratoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Prato");
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.Prato", b =>
                {
                    b.HasOne("QuentinhasDaTininha.Dominio.Entidades.Categoria", "Categoria")
                        .WithMany("Pratos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuentinhasDaTininha.Dominio.Entidades.GrupoAcompanhamento", "GrupoAcompanhamento")
                        .WithMany("Pratos")
                        .HasForeignKey("GrupoAcompanhamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Categoria");

                    b.Navigation("GrupoAcompanhamento");
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.PratoAcompanhamento", b =>
                {
                    b.HasOne("QuentinhasDaTininha.Dominio.Entidades.Acompanhamento", "Acompanhamento")
                        .WithMany("PratoAcompanhamentos")
                        .HasForeignKey("AcompanhamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuentinhasDaTininha.Dominio.Entidades.Prato", "Prato")
                        .WithMany("PratoAcompanhamentos")
                        .HasForeignKey("PratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acompanhamento");

                    b.Navigation("Prato");
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.PrecoPrato", b =>
                {
                    b.HasOne("QuentinhasDaTininha.Dominio.Entidades.Prato", "Prato")
                        .WithMany("Precos")
                        .HasForeignKey("PratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prato");
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.Acompanhamento", b =>
                {
                    b.Navigation("GruposAcompanhamentoItens");

                    b.Navigation("PratoAcompanhamentos");
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.CardapioDia", b =>
                {
                    b.Navigation("CardapiosDiaPratos");
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.Categoria", b =>
                {
                    b.Navigation("Pratos");
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.FreteBairro", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Ceps");
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.GrupoAcompanhamento", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("Pratos");
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.Pedido", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.Prato", b =>
                {
                    b.Navigation("CardapiosDiaPratos");

                    b.Navigation("PratoAcompanhamentos");

                    b.Navigation("Precos");
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.UsuarioAdministrativo", b =>
                {
                    b.Navigation("HistoricosAlteracao");
                });
#pragma warning restore 612, 618
        }
    }
}
