// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuentinhasDaTininha.Infraestrutura.Persistencia;

#nullable disable

namespace QuentinhasDaTininha.Infraestrutura.Persistencia.Migrations
{
    [DbContext(typeof(QuentinhasDaTininhaDbContext))]
    partial class QuentinhasDaTininhaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.Acompanhamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstaDisponivel")
                        .HasColumnType("boolean");

                    b.Property<string>("MotivoIndisponibilidade")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("OrdemExibicao")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecoAdicional")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("acompanhamento", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.CardapioDia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DiaSemana")
                        .IsUnique();

                    b.ToTable("cardapio_dia", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.CardapioDiaPrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardapioDiaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EstaDisponivel")
                        .HasColumnType("boolean");

                    b.Property<int>("OrdemExibicao")
                        .HasColumnType("integer");

                    b.Property<Guid>("PratoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PratoId");

                    b.HasIndex("CardapioDiaId", "PratoId")
                        .IsUnique();

                    b.ToTable("cardapio_dia_prato", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EstaAtiva")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrdemExibicao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("categoria", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.ConfiguracaoRestaurante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AceitaPedidos")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cep")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("MensagemAberto")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("MensagemFechado")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("ModoFuncionamento")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UrlImagemCapa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UrlLogotipo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Whatsapp")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("configuracao_restaurante", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.FechamentoExcepcional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataFechamento")
                        .HasColumnType("date");

                    b.Property<bool>("DiaInteiro")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly?>("HoraFim")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<string>("MensagemCliente")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Motivo")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("DataFechamento");

                    b.ToTable("fechamento_excepcional", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.HistoricoAlteracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Acao")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DadosAnteriores")
                        .HasColumnType("text");

                    b.Property<string>("DadosNovos")
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("EntidadeId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoEntidade")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("UsuarioAdministrativoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioAdministrativoId");

                    b.HasIndex("TipoEntidade", "EntidadeId");

                    b.ToTable("historico_alteracao", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.HorarioFuncionamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly>("HoraAbertura")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraFechamento")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DiaSemana", "HoraAbertura", "HoraFechamento")
                        .IsUnique();

                    b.ToTable("horario_funcionamento", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.Prato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EhDestaque")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstaDisponivel")
                        .HasColumnType("boolean");

                    b.Property<string>("MotivoIndisponibilidade")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("OrdemExibicao")
                        .HasColumnType("integer");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("UrlImagem")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EstaAtivo");

                    b.HasIndex("EstaDisponivel");

                    b.HasIndex("Nome");

                    b.HasIndex("OrdemExibicao");

                    b.ToTable("prato", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.PratoAcompanhamento", b =>
                {
                    b.Property<Guid>("PratoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcompanhamentoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EhObrigatorio")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstaIncluido")
                        .HasColumnType("boolean");

                    b.Property<int?>("QuantidadeMaxima")
                        .HasColumnType("integer");

                    b.HasKey("PratoId", "AcompanhamentoId");

                    b.HasIndex("AcompanhamentoId");

                    b.ToTable("prato_acompanhamento", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.UsuarioAdministrativo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("UltimoAcessoEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuario_administrativo", (string)null);
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.CardapioDiaPrato", b =>
                {
                    b.HasOne("QuentinhasDaTininha.Dominio.Entidades.CardapioDia", "CardapioDia")
                        .WithMany("CardapiosDiaPratos")
                        .HasForeignKey("CardapioDiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuentinhasDaTininha.Dominio.Entidades.Prato", "Prato")
                        .WithMany("CardapiosDiaPratos")
                        .HasForeignKey("PratoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CardapioDia");

                    b.Navigation("Prato");
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.HistoricoAlteracao", b =>
                {
                    b.HasOne("QuentinhasDaTininha.Dominio.Entidades.UsuarioAdministrativo", "UsuarioAdministrativo")
                        .WithMany("HistoricosAlteracao")
                        .HasForeignKey("UsuarioAdministrativoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UsuarioAdministrativo");
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.Prato", b =>
                {
                    b.HasOne("QuentinhasDaTininha.Dominio.Entidades.Categoria", "Categoria")
                        .WithMany("Pratos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.PratoAcompanhamento", b =>
                {
                    b.HasOne("QuentinhasDaTininha.Dominio.Entidades.Acompanhamento", "Acompanhamento")
                        .WithMany("PratoAcompanhamentos")
                        .HasForeignKey("AcompanhamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuentinhasDaTininha.Dominio.Entidades.Prato", "Prato")
                        .WithMany("PratoAcompanhamentos")
                        .HasForeignKey("PratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acompanhamento");

                    b.Navigation("Prato");
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.Acompanhamento", b =>
                {
                    b.Navigation("PratoAcompanhamentos");
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.CardapioDia", b =>
                {
                    b.Navigation("CardapiosDiaPratos");
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.Categoria", b =>
                {
                    b.Navigation("Pratos");
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.Prato", b =>
                {
                    b.Navigation("CardapiosDiaPratos");

                    b.Navigation("PratoAcompanhamentos");
                });

            modelBuilder.Entity("QuentinhasDaTininha.Dominio.Entidades.UsuarioAdministrativo", b =>
                {
                    b.Navigation("HistoricosAlteracao");
                });
#pragma warning restore 612, 618
        }
    }
}
